In [64]:
import pandas as pd

In [157]:
sandwich = pd.read_csv(r'a-fanning-doughnut-v3-a0460e5\Analysis-Final\myData\12_20250515_globalDoughnutData_2000-2022.csv')

In [158]:
sandwich[sandwich['indicator'] == 'foodInsecurity']

,domain,dimension,type,group,grpCode,indicator,indCode,unit,date,value,boundary,shortfallOvershoot_pct
322,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2000,NaN,0.0,NaN
323,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2001,NaN,0.0,NaN
324,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2002,NaN,0.0,NaN
325,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2003,NaN,0.0,NaN
326,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2004,NaN,0.0,NaN
327,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2005,NaN,0.0,NaN
328,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2006,NaN,0.0,NaN
329,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2007,NaN,0.0,NaN
330,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2008,NaN,0.0,NaN
331,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2009,NaN,0.0,NaN
332,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2010,NaN,0.0,NaN
333,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2011,NaN,0.0,NaN
334,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2012,NaN,0.0,NaN
335,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2013,NaN,0.0,NaN
336,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2014,NaN,0.0,NaN
337,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2015,22.24,0.0,22.2
338,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2016,23.14,0.0,23.1
339,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2017,23.78,0.0,23.8
340,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2018,24.02,0.0,24.0
341,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2019,25.34,0.0,25.3
342,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2020,27.07,0.0,27.1
343,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2021,28.87,0.0,28.9
344,social,food,global doughnut,World,WLD,foodInsecurity,NU2,percent,2022,29.36,0.0,29.4

In [159]:
sandwich = sandwich[sandwich['group'] == 'World']
sandwich = sandwich[sandwich['type'] == 'global doughnut']

In [160]:
sandwich = sandwich[['domain', 'indicator', 'date', 'value']]

In [161]:
# have only start and end date lines
sandwich.sort_values(['indicator', 'date'], inplace=True)
# remove racialInequality indicator because all values of column value are equal to nan and
# therefore is unusable
sandwich = sandwich[sandwich['indicator'] != 'racialInequality']
#filter dataset to include only desired dates
for indicator in sandwich['indicator'].unique() :
    earliest_value, early_date = sandwich2.loc[
        (sandwich2['indicator'] == indicator) & sandwich2['value'].notna()
    ].sort_values('date')[['value', 'date']].iloc[0]
    # all indicators have values for 2022 (last date for dataset)
    sandwich = sandwich[~((sandwich['indicator'] == indicator) & (sandwich['date'] != early_date) & (sandwich['date'] != 2022))]

In [162]:
sandwich

         domain         indicator  date  value
368      social          UHCindex  2000  79.05
390      social          UHCindex  2022  28.07
391      social     adultLiteracy  2000  23.13
413      social     adultLiteracy  2022  16.15
161  ecological           blueDev  2000  17.83
..          ...               ...   ...    ...
321      social  undernourishment  2022   9.62
621      social        urbanSlums  2000  39.71
643      social        urbanSlums  2022  32.07
465      social         youthNEET  2005  24.97
482      social         youthNEET  2022  20.31

[68 rows x 4 columns]

In [163]:
eco_sand = sandwich[sandwich['domain'] == 'ecological'].copy()
social_sand = sandwich[sandwich['domain'] == 'social'].copy()

In [164]:
eco_sand.sort_values(['indicator', 'date'], inplace=True)
social_sand.sort_values(['indicator', 'date'], inplace=True)

In [165]:
eco_sand.reset_index(drop=True, inplace=True)
social_sand.reset_index(drop=True, inplace=True)

In [169]:
# we see multiple nan values in value axis and as such we need to impute them with the earliest or latest value 
# depending on the line
eco_sand[social_sand.isna().any(axis=1)]

C:\Users\User\AppData\Local\Temp\ipykernel_11044\1237497645.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  eco_sand[social_sand.isna().any(axis=1)]

Empty DataFrame
Columns: [domain, indicator, date, value]
Index: []

In [ ]:
!git add Sandwich.ipynb
!git commit -m "Add m